apiVersion: v1
kind: Service
metadata:
  name: go-reader-app
  labels:
    app: go-reader
    role: application
    tier: application
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: go-reader
    role: application
    tier: application
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-reader-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: go-reader
        role: application
        tier: application
    spec:
      containers:
      - name: app
        image: mattwittmann.com/go-reader:v1
        ports:
        - containerPort: 8080
